# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30cd42e2e94fc4dd1a2a4d972829da898f211aef279287e352b46354f03e5a27301815393af5e5677c7888c14f916a22f9105d8cdf2bfffabe7a5cb6235ac5e4

test:
  secret_key_base: 52db86298f6275cd257f6f6fe5daadfaeea9dae7524e0b730e862160a5f4f2dacc79b472da055fb48e889bbcd9a9eb7197c594e5dcb63fd425eab245ddb0fe61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
